server:
  servlet:
    context-path: /todo-app/
#  ssl:
#    enabled: true
#    key-store: classpath:localhost.p12
#    key-store-type: PKCS12
#    key-store-password: changeit
#    session:
#      cookie:
#        secure: true
      
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todo_app_db
    username: admin
    password: admin
  session:
    store-type: jdbc
    timeout:
      seconds: 90
    jdbc:
      initialize-schema: always     
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      
management:
   security:
      enabled: false