#server:
#  servlet:
#    context-path: /todo-app/
#      
#  port: 8080
spring:
  session:
    store-type: jdbc
    timeout:
      seconds: 90
    jdbc:
      initialize-schema: always     
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create